name: Publish to NuGet

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Publish to NuGet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and Test (optional)
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=1.0.0 --no-build -o out

    - name: Push to NuGet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: IceCream/IceCream.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}  
        DOTNET_VERSION: '7.0.x'
